### ISSUE TITLE
Emitting dts files

### ISSUE THREAD

**Issue by cometkim** [cometkim/nanobundle#4]
questions:

- Should this do dts bundling? (even there are limitations)
- If not, is it really necessary?

**Comment by jrson83** [comment]
Any news on this?

**Comment by cometkim** [comment]
@jrson83 nanobundle is well emitting dts files as necessary

Do you need something else?

**Comment by jrson83** [comment]
@cometkim sorry I can't find anything about dts bundling in the docs. Is it possible to bundle `.d.ts` files with `nanobundle` like `dts-bundle-generator` does?

**Comment by cometkim** [comment]
I had considered it, but dts-bundling isn't compatible with multiple entries and TypeScript's NodeNext resolution.

Welcome if you have any approach to do it.

**Comment by jrson83** [comment]
Thanks, I did not know, but I just saw your [PR related to tsconfck](https://github.com/dominikg/tsconfck/pull/73).

My use-case is a TypeScript module meant for browser and node environment. I have setup a [minimal example repo](https://github.com/jrson83/nanobundle-dts-test).
If you can take a look would be great.

The file `src/index.ts` exports `src/client.ts` and `src/router.ts` is meant for browser.
The file `src/server.ts` is meant for node.

When using `yarn run build:nanobundle`, nanobundle generates the output files with declarations enabled.
It produces multiple `d.ts` files for the browser bundle (not one bundled `d.ts` file):

- `lib/client.d.ts`
- `lib/index.d.ts`
- (in addition `lib/server.d.ts`)

As a workaround I tested various settings with `dts-bundle-generator`. If you run `yarn run build:nanobundle:dts`, nanobundle generates the output files with declarations disabled, following `dts-bundle-generator`, generates one `d.ts` bundle for browser and one `d.ts` bundle for node. But it takes up to 20 seconds for the command:

- `lib/index.d.ts` (`lib/client.d.ts` is included)
- (in addition `lib/server.d.ts`)

I also tested `unbuild`, as a comparison you can run `yarn run build:unbuild`, it will also output one bundled `lib/index.d.ts` and `lib/server.d.ts`.

Maybe I get this wrong and it's okay how nanobundle bundles the `d.ts`. I was just wondering, since unbuild bundles the `d.ts` files, as I expected.

**Comment by cometkim** [comment]
It seems to use [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts). And seems like an ideal option to do dts bundling, but I wouldn't make it the default for several reasons.
- There is no need to bundle dts (yet)
- It doesn't support all use case of typescript. Because TypeScript expects files to be split, you can run into unexpected conflicts with merged files.
- Maybe slow (20 more seconds for build... is way far)

I could experiment with the rollup for dts and introduce it with the `--experimental-dts-bundling` flag, but it's not a high priority.

**Comment by jrson83** [comment]
> I could experiment with the rollup for dts and introduce it with the --experimental-dts-bundling flag, but it's not a high priority.

That would be great! Thank you.
